---
- name: Install Apache and MySQL
  hosts: all
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  
  roles:
    - /home/halsningar/DevOps/lesson13/apache
    - /home/halsningar/DevOps/lesson13/mysql
