# Stage 1: Build the application
FROM node:16 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Prepare the final image
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
