# Image 2
FROM debian:11

# Install nginx
RUN apt-get update && apt-get install -y nginx && apt-get clean

# Creating folder and add index.html
RUN mkdir -p /opt/www \
    && echo "<html><body><h1>Welcome to lesson16 <p><b>Image II</b></p></h1></body></html>" > /opt/www/index.html

# Set up nginx
RUN mkdir -p /etc/nginx/conf.d
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Open 80
EXPOSE 80

# Setting launch nginx up through ENTRYPOINT
ENTRYPOINT ["nginx", "-g", "daemon off;"]
