apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define('DB_NAME', '{{ .Values.mysql.database }}');
    define('DB_USER', '{{ .Values.mysql.username }}');
    define('DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD'));
    define('DB_HOST', 'mysql');
?>